### ISSUE TITLE
demo API errors on Kube apply

### ISSUE THREAD

**Issue by sublimino** [s-irvine/katacoda-test#1]
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  15s                default-scheduler  Successfully assigned default/demo-api-7cff5ddd4d-chv5g to master
  Normal   Pulling    13s (x2 over 14s)  kubelet, master    pulling image "127.0.0.1:30002/library/demo-api:secure"
  Normal   Pulled     13s (x2 over 14s)  kubelet, master    Successfully pulled image "127.0.0.1:30002/library/demo-api:secure"
  Normal   Created    12s (x2 over 14s)  kubelet, master    Created container
  Normal   Started    12s (x2 over 14s)  kubelet, master    Started container
  Warning  BackOff    9s (x3 over 12s)   kubelet, master    Back-off restarting failed container
```

**Comment by molepigeon** [comment]
Logs from the pod:

```
internal/net.js:17
    throw new RangeError('"port" argument must be >= 0 and < 65536');
    ^

RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1383:5)
    at Server.listen (/usr/src/app/node_modules/restify/lib/server.js:313:32)
    at Object.<anonymous> (/usr/src/app/index.js:13:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

**Comment by molepigeon** [comment]
I had a go at this, but didn't get far. I don't think we need to access the demo-api itself, so if we can't figure it out I think we can get away with changing the command to something like `sleep 1000` so that at least it goes into running state.
